name: 12 on stretch

on:
  push:
    paths:
      - functions.sh
      - test-build.sh
      - test-image.bats
      - 12/stretch/Dockerfile
  pull_request:
    paths:
      - functions.sh
      - test-build.sh
      - test-image.bats
      - 12/stretch/Dockerfile

jobs:
  build:
    name: 12 on stretch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson('{"arch":["amd64","arm32v7","arm64v8"]}')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install bats
        run: sudo apt-get install bats

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Write experimental docker flag
        run: |
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json

      - name: Restart docker daemon
        run: sudo systemctl restart docker

      - name: Build and test
        run: ./test-build.sh 12 stretch ${{ matrix.arch }}
