name: Automatically update Docker image versions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nodejs'
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run automation script
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: updt
        with:
          result-encoding: string
          script: |
            const { default: script } = await import(`${process.env.GITHUB_WORKSPACE}/build-automation.mjs`);
            return script(github);

      - name: Create update PR
        id: cpr
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          author: "Node.js GitHub Bot <nodejs-github-bot@users.noreply.github.com>"
          branch: update-branch
          base: main
          commit-message: "feat: Node.js ${{ steps.updt.outputs.result }}"
          title: "feat: Node.js ${{ steps.updt.outputs.result }}"
          delete-branch: true
          team-reviewers: |
            nodejs/docker
