name: Automatically update Docker image versions

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nodejs'

    steps:
      - uses: actions/checkout@v3

      - name: Run automation script
        uses: actions/github-script@v6
        id: updt
        with:
          script: |
            const { default: script } = await import(`${process.env.GITHUB_WORKSPACE}/build-automation.mjs`);
            return script(github);

      - name: Create update PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-branch
          base: main
          commit-message: "feat: Node.js ${{ steps.updt.outputs.result.updatedVersions.join(', ') }}"
          title: "feat: Node.js ${{ steps.updt.outputs.result.updatedVersionsString }}"
          delete-branch: true
          team-reviewers: |
            @nodejs/docker
