name: Create official images PR

on:
  pull_request_target:
    types:
      - closed

    paths:
      - ".github/workflows/official-pr.yml"
      - "**/Dockerfile"
      - "**/docker-entrypoint.sh"
      - "versions.json"
      - "stackbrew.js"

jobs:
  pr:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nodejs' && github.event.pull_request.merged_by != ''
    permissions:
      pull-requests: write

    steps:
      - name: Checkout the docker-node repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          path: docker-node
          ref: ${{ github.base_ref }}
          fetch-depth: 50

      - name: Checkout the official-images repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          path: official-images
          repository: docker-library/official-images

      - name: Generate Stackbrew for diff
        run: |
          cd docker-node
          ./stackbrew.js > ../official-images/library/node

      - name: Create PR in official-images
        id: create-pr
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.GH_API_TOKEN }}
          push-to-fork: nodejs/official-images
          path: official-images
          branch: node
          commit-message: "Node: ${{ github.event.pull_request.title }}"
          title: "Node: ${{ github.event.pull_request.title }}"
          body: |
            Pull Request: ${{ github.event.pull_request.html_url }}
            @LaurentGoderre @PeterDaveHello @SimenB @Starefossen @nschonni @ttshivers

      - name: PR details
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"

      - name: Create PR comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        if: ${{ steps.create-pr.outputs.pull-request-url != '' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Created PR on the official-images repo (${{ steps.create-pr.outputs.pull-request-url }}). See https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what if you are wondering when it will be available on the Docker Hub.
